In [1]:
import numpy as np
a = np.array([20,40,60,80])

print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a))

200
20
80
4
50.0
[ 20  60 120 200]


In [3]:
#Example:1
import numpy as np

a = [100,230,250,850,130,140]
b = [10,30,40,50,20,60]

price = np.array(a)
quantity = np.array(b)

print(f"This is a price..{price}", "\n",f"This is quantity..{quantity}")
print()
c = np.cumprod([price,quantity], axis = 0)
print(c)
print(c[1].sum())

This is a price..[100 230 250 850 130 140] 
 This is quantity..[10 30 40 50 20 60]

[[  100   230   250   850   130   140]
 [ 1000  6900 10000 42500  2600  8400]]
71400


In [7]:
#Example:2
import numpy as np

a = [100,230,250,850,130,140]
b = [10,30,40,50,20,60]

price = np.array(a)
quantity = np.array(b)

print(f"This is a price..{price}", "\n",f"This is quantity..{quantity}")
print()
c = np.cumsum([price,quantity], axis = 0)
print(c)
print()
print("This is sum:",c[1].sum())

This is a price..[100 230 250 850 130 140] 
 This is quantity..[10 30 40 50 20 60]

[[100 230 250 850 130 140]
 [110 260 290 900 150 200]]

This is sum: 1910
